version: '3.8'
services:
  user-service:
    build: ./userService
    ports:
      - "8001:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - REDIS_HOST=redis_cache
    depends_on:
      - user-db
      - redis_cache

  user-db:
    image: postgres
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  product-service:
    build: ./productService
    ports:
      - "8002:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product_db
      - SPRING_DATASOURCE_USERNAME=product
      - SPRING_DATASOURCE_PASSWORD=password
      - MONGODB_URI=mongodb://product-review-db:27017/product_reviews
      - REDIS_HOST=redis_cache
    depends_on:
      - product-db
      - product-review-db
      - redis_cache

  product-db:
    image: postgres
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=password

  product-review-db:
    image: mongo

  order-service:
    build: ./orderService
    ports:
      - "8003:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=order
      - SPRING_DATASOURCE_PASSWORD=password
      - REDIS_HOST_ORDER_CACHE=orderCache  # Reference to the order_cache service
      - REDIS_PORT_ORDER_CACHE=6379  # Default Redis port for order_cache
      - REDIS_HOST_REDIS_CACHE=redisCache  # Reference to the redis_cache service
      - REDIS_PORT_REDIS_CACHE=6379  # Default Redis port for redis_cache
    depends_on:
      - order-db
      - order_cache
      - redis_cache

  order-db:
    image: postgres
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=order
      - POSTGRES_PASSWORD=password

  order_cache:
    image: redis:latest
    container_name: orderCache
    ports:
      - "6380:6379"  # External port 6380 mapped to internal Redis port 6379

  redis_cache:
    image: redis:latest
    container_name: redisCache
    ports:
      - "6381:6379"  # External port 6381 mapped to internal Redis port 6379

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisInsight
    ports:
      - "5540:5540"
    restart: always


  payment-service:
    build: ./paymentService
    ports:
      - "8004:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-db:5432/payment_db
      - SPRING_DATASOURCE_USERNAME=payment
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - payment-db
      - rabbitmq

  payment-db:
    image: postgres
    environment:
      - POSTGRES_DB=payment_db
      - POSTGRES_USER=payment
      - POSTGRES_PASSWORD=password

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
