apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-cache
  template:
    metadata:
      labels:
        app: order-cache
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          command:
            - "redis-server"
            - "--appendonly"
            - "yes"
            - "--maxmemory"
            - "256mb"  # Limit Redis memory usage, adjust as needed
            - "--maxmemory-policy"
            - "allkeys-lru"  # Key eviction policy when max memory is reached
