apiVersion: v1
kind: Service
metadata:
  name: order-cache
spec:
  selector:
    app: order-cache
  ports:
    - port: 6379      # Redis default port
      targetPort: 6379
  clusterIP: None     # Headless service for direct pod communication
