apiVersion: v1
kind: Service
metadata:
  name: redisinsight
spec:
  selector:
    app: redisinsight
  ports:
    - port: 5540       # RedisInsight UI port
      targetPort: 5540
  clusterIP: None      # Headless service for direct pod communication
