apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: mennan0809/order-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://order-db:5432/order_db
            - name: SPRING_DATASOURCE_USERNAME
              value: order
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: REDIS_HOST_ORDER_CACHE
              value: order-cache
            - name: REDIS_PORT_ORDER_CACHE
              value: "6379"
            - name: REDIS_HOST_REDIS_CACHE
              value: redis-cache
            - name: REDIS_PORT_REDIS_CACHE
              value: "6379"
