apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-review-db
spec:
  serviceName: "product-review-db"
  replicas: 1
  selector:
    matchLabels:
      app: product-review-db
  template:
    metadata:
      labels:
        app: product-review-db
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
