apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672       # AMQP Port
      targetPort: 5672
    - port: 15672      # Management Console Port
      targetPort: 15672
  clusterIP: None       # Headless service for direct pod communication
