apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: user-db  # Adjust according to the specific database
  ports:
    - port: 5432
  clusterIP: None  # Makes the service headless for StatefulSet
